title: Government Report Dataset
logo: 
description: A long document summarization dataset.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
data_url: https://drive.google.com/file/d/1ik8uUVeIU-ky63vlnvxtfN2ZN-TUeov2/view?usp=sharing
